Music/Controllers/AlbumController.cs
using Microsoft.AspNetCore.Mvc;
using Music.Data.DataModels;
using Music.Services.Interfaces;
using Music.Services.ViewModels;
using System.Security.Claims;

namespace Music.Controllers
{
    public class AlbumController : Controller
    {
        public IAlbumService albumService { get; set; }

        public AlbumController(IAlbumService service)
        {
            albumService = service;
        }
        public IActionResult Index()
        {

            List<Album> albums = albumService.GetAll();

            return this.View(albums);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AlbumViewModel albumVM)
        {
            if (!albumService.CheckArtist(albumVM.ArtistName))
            {
                ModelState.AddModelError("ArtistName", "An artist with this name doesn't exist");
            }
            if (albumService.CheckArtist(albumVM.ArtistName))
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                albumVM.CreatorID = userId;
                await albumService.CreateAsync(albumVM);
                TempData["done"] = "An Album Has Been Created Successfully!";
                return RedirectToAction("Index");
            }
            return View(albumVM);
        }

        public IActionResult Edit(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!albumService.CheckId(id))
            {
                return NotFound();
            }
            return View(albumService.GetById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(AlbumViewModel albumVM)
        {
            if (!albumService.CheckArtist(albumVM.ArtistName))
            {
                ModelState.AddModelError("ArtistName", "An artist with this name doesn't exist");

            }
            if (albumService.CheckArtist(albumVM.ArtistName))
            {
                await albumService.UpdateAsync(albumVM);
                TempData["done"] = "An Album Has Been Edited Successfully!";
                return RedirectToAction("Index");
            }
            return View(albumVM);
        }
        public IActionResult Delete(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!albumService.CheckId(id))
            {
                return NotFound();
            }
            return View(albumService.GetById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(string? id)
        {
            var obj = albumService.GetById(id);
            if (obj == null)
            {
                return NotFound();
            }
            await albumService.DeleteAlbum(id);
            TempData["done"] = "An Album Has Been Deleted Successfully!";
            return RedirectToAction("Index");

        }
    }
}

Music/Controllers/ArtistController.cs
using Microsoft.AspNetCore.Mvc;
using Music.Data.DataModels;
using Music.Services.Interfaces;
using Music.Services.ViewModels;
using System.Security.Claims;

namespace Music.Controllers
{
    public class ArtistController : Controller
    {
        public IArtistService artistService { get; set; }

        public ArtistController(IArtistService service)
        {
            artistService = service;
        }
        public IActionResult Index()
        {

            List<Artist> artists = artistService.GetAll();

            return this.View(artists);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ArtistViewModel artistVM)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            artistVM.CreatorID = userId;
            await artistService.CreateAsync(artistVM);
            TempData["done"] = "An Artist Has Been Created Successfully!";
            return RedirectToAction("Index");

        }

        public IActionResult Edit(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!artistService.CheckId(id))
            {
                return NotFound();
            }
            return View(artistService.GetById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ArtistViewModel artistVM)
        {
            await artistService.UpdateAsync(artistVM);
            TempData["done"] = "An Artist Has Been Edited Successfully!";
            return RedirectToAction("Index");
        }
        public IActionResult Delete(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!artistService.CheckId(id))
            {
                return NotFound();
            }
            return View(artistService.GetById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(string? id)
        {
            var obj = artistService.GetById(id);
            if (obj == null)
            {
                return NotFound();
            }
            await artistService.DeleteArtist(id);
            TempData["done"] = "An Artist Has Been Deleted Successfully!";
            return RedirectToAction("Index");

        }
    }
}

Music/Controllers/SongController.cs
using Microsoft.AspNetCore.Mvc;
using Music.Data.DataModels;
using Music.Services.Interfaces;
using Music.Services.ViewModels;
using System.Security.Claims;

namespace Music.Controllers
{
    public class SongController : Controller
    {
        public ISongService songService { get; set; }

        public SongController(ISongService service)
        {
            songService = service;
        }
        public IActionResult Index()
        {

            List<Song> songs = songService.GetAll();

            return this.View(songs);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SongViewModel songVM)
        {
            if (!songService.CheckAlbum(songVM.AlbumName))
            {
                ModelState.AddModelError("AlbumName", "An album with this name doesn't exist");
            }
            if (!songService.CheckArtist(songVM.ArtistName))
            {
                ModelState.AddModelError("ArtistName", "An artist with this name doesn't exist");
            }
            if (songService.CheckAlbum(songVM.AlbumName) && songService.CheckArtist(songVM.ArtistName))
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                songVM.CreatorID = userId;
                await songService.CreateAsync(songVM);
                TempData["done"] = "A Song Has Been Created Successfully!";
                return RedirectToAction("Index");
            }
            return View(songVM);
        }

        public IActionResult Edit(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!songService.CheckId(id))
            {
                return NotFound();
            }
            return View(songService.GetById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SongViewModel songVM)
        {
            if (!songService.CheckAlbum(songVM.AlbumName))
            {
                ModelState.AddModelError("AlbumName", "An album with this name doesn't exist");
            }
            if (!songService.CheckArtist(songVM.ArtistName))
            {
                ModelState.AddModelError("ArtistName", "An artist with this name doesn't exist");
            }
            if (songService.CheckAlbum(songVM.AlbumName) && songService.CheckArtist(songVM.ArtistName))
            {
                await songService.UpdateAsync(songVM);
                TempData["done"] = "A Song Has Been Edited Successfully!";
                return RedirectToAction("Index");
            }
            return View(songVM);
        }
        public IActionResult Delete(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!songService.CheckId(id))
            {
                return NotFound();
            }
            return View(songService.GetById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(string? id)
        {
            var obj = songService.GetById(id);
            if (obj == null)
            {
                return NotFound();
            }
            await songService.DeleteSong(id);
            TempData["done"] = "A Song Has Been Deleted Successfully!";
            return RedirectToAction("Index");

        }
    }
}

Music/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using Music.Data.DataModels;
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MusicWiki</title>
    <link rel="stylesheet" href="~/css/bootswatch.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Music.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
                <a class="navbar-brand text-primary" asp-controller="Home" asp-action="Index">MusicWiki</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
        </li>
        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Song" asp-action="Index">Songs</a>
        </li>
        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artist" asp-action="Index">Artists</a>
        </li>
        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Album" asp-action="Index">Albums</a>
        </li>
        @if (User.IsInRole("Admin"))
        {
        <li class="nav-item">
                                <button class="btn btn-primary" id="fetchButton">Fetch Data</button>
        </li>
        }
      </ul>
                    <partial name="_LoginPartial" />
    </div>
  </div>
        </nav>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-light">
        <div class="container">
            &copy; 2023 - MusicWiki - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        document.getElementById("fetchButton").addEventListener("click", function () {
            fetch("/api/albums", {
                method: "POST"
            })
                .then(response => {
                    if (response.ok) {
                        console.log("Request succeeded!");
                    } else {
                        response.json().then(data => {
                            console.log("Error occurred:", data.ErrorMessage);
                        });
                    }
                })
                .catch(error => {
                    console.log("Error occurred:", error);
                });
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Music/Views/Shared/_Notification.cshtml
@if (TempData["done"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.options = {
			"closeButton": false,
			"debug": false,
			"newestOnTop": false,
			"progressBar": false,
			"positionClass": "toast-bottom-left",
			"preventDuplicates": false,
			"onclick": null,
			"showDuration": "300",
			"hideDuration": "1000",
			"timeOut": "5000",
			"extendedTimeOut": "1000",
			"showEasing": "swing",
			"hideEasing": "linear",
			"showMethod": "fadeIn",
			"hideMethod": "fadeOut"
		}
		toastr.success('@TempData["done"]');
	</script>
}